### ISSUE TITLE
Server manually closed but still getting errors from the proxy

### ISSUE THREAD

**Issue by binarykitchen** [andrewrk/connect-proxy#31]
I manually closed the express server with `server.close()`, yet the proxy throws an error. I guess the proxy is not listening to the server's shutdown process?

```
Error: connect ECONNREFUSED
    at errnoException (net.js:905:11)
    at afterConnect (net.js:896:19)
---------------------------------------------
    at Readable.on (_stream_readable.js:708:33)
    at http.js:1758:12
    at process._tickDomainCallback (node.js:486:13)
---------------------------------------------
    at ClientRequest.onSocket (http.js:1735:11)
    at Agent.addRequest (http.js:1274:9)
    at new ClientRequest (http.js:1421:16)
    at exports.request (http.js:1848:10)
    at /home/xxx/node_modules/proxy-middleware/index.js:50:17
 ...
```

**Comment by Frizi** [comment]
I closed my server manually by server.close(), but node process didn't exited. It happens only when proxy-middleware is active. Proxy requests are probably still hanging around.

**Comment by binarykitchen** [comment]
@andrewrk ?
